# Generated by Django 4.0.6 on 2022-07-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuriStackApp_accounts', '0002_remove_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
